field: 0a48bd97-a148-4d00-9a3a-c4ec21fdd7d5 # Post Content
fieldLayouts:
  40af47b7-d59c-467d-ba74-0632f8950fc6:
    tabs:
      -
        elements:
          -
            fieldUid: dcf8d2b1-fe1a-4c0d-bcc0-2bbce3821a8e # Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
fields:
  dcf8d2b1-fe1a-4c0d-bcc0-2bbce3821a8e: # Image
    contentColumnType: string
    fieldGroup: null
    handle: image
    instructions: ''
    name: Image
    searchable: false
    settings:
      allowSelfRelations: false
      allowUploads: true
      allowedKinds:
        - image
      defaultUploadLocationSource: 'volume:66d4d2c3-31e8-4504-afdb-355b7727b865' # common
      defaultUploadLocationSubpath: ''
      limit: ''
      localizeRelations: false
      previewMode: full
      restrictFiles: '1'
      selectionLabel: ''
      showSiteMenu: false
      showUnpermittedFiles: false
      showUnpermittedVolumes: false
      singleUploadLocationSource: 'volume:e1fb144f-7b23-4b13-87fa-176ee43d895f' # Blog
      singleUploadLocationSubpath: ''
      source: null
      sources: '*'
      targetSiteId: null
      useSingleFolder: true
      validateRelatedElements: false
      viewMode: list
    translationKeyFormat: null
    translationMethod: site
    type: craft\fields\Assets
handle: image
name: Image
sortOrder: 2
