fieldLayouts:
  394f88c4-1b4d-40ac-bd09-d54bcfd52760:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\EntryTitleField
            warning: null
            width: 100
          -
            fieldUid: dd4a4ff0-c7a7-44e9-ae2e-56a8e3bda66e # Faq Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: c685371a-c6b6-4e08-867b-f48f1a3a6feb # Faq Summary
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 00074bcf-c0a5-4b25-961c-a5a598354691 # Faq Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: e931a5d4-8efe-45b2-b58e-fb79d8903fd3 # Faq qanda
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: Content
        sortOrder: 1
handle: frequentlyAskedQuestion
hasTitleField: true
name: 'Frequently Asked Question'
section: 1796c917-d33d-41f6-ad7d-d30e9bbb7ef6 # Frequently Asked Question
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
