fieldLayouts:
  ab3aa4f3-a6cf-410f-afca-ad54debeeead:
    tabs:
      -
        elements:
          -
            fieldUid: 270d78ce-6d1b-43f3-b042-dcc1013662d8 # Small Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 340fa19a-d07d-4c2e-af52-4b799937ff2a # small Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: fe2ab5bd-a2b7-4bd6-9a33-e4f0dc2ad2a7 # Long Title
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
          -
            fieldUid: 8cd722e0-22c9-4e24-9a2d-3a565840c3bf # Large Image
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            warning: null
            width: 100
        name: 'Slider Content'
        sortOrder: 1
handle: homeSlider
hasTitleField: true
name: 'Home Slider'
section: d3e699ad-2b04-4336-8b4d-debcc4500946 # Home Slider
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
