contentColumnType: string(60)
fieldGroup: ab7a340d-1d26-4d8b-acc0-548666d2519d # Common
handle: phoneTwo
instructions: ''
name: 'Phone Two'
searchable: false
settings:
  byteLimit: null
  charLimit: 15
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: 'Second Phone Number'
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
