contentColumnType: string
fieldGroup: bc3cc6d3-c33f-4507-985c-34532b32e14d # Home Slider Post Fields
handle: smallImage
instructions: ''
name: 'small Image'
searchable: false
settings:
  allowSelfRelations: false
  allowUploads: true
  allowedKinds:
    - image
  defaultUploadLocationSource: 'volume:66d4d2c3-31e8-4504-afdb-355b7727b865' # common
  defaultUploadLocationSubpath: ''
  limit: '1'
  localizeRelations: false
  previewMode: full
  restrictFiles: '1'
  selectionLabel: ''
  showSiteMenu: false
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  singleUploadLocationSource: 'volume:1dc02708-8f0a-4f9a-a607-6c77714356bd' # Home
  singleUploadLocationSubpath: ''
  source: null
  sources: '*'
  targetSiteId: null
  useSingleFolder: true
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: site
type: craft\fields\Assets
