enableVersioning: true
handle: about
name: About
propagationMethod: all
siteSettings:
  950c6040-e386-4f1f-b60a-fec96f0dc055: # democraft
    enabledByDefault: true
    hasUrls: true
    template: _singles/about
    uriFormat: about
type: single
