enableVersioning: true
handle: contactus
name: 'Contact Us'
propagationMethod: all
siteSettings:
  950c6040-e386-4f1f-b60a-fec96f0dc055: # democraft
    enabledByDefault: true
    hasUrls: true
    template: _singles/contact
    uriFormat: contact-us
type: single
