enableVersioning: true
handle: services
name: Services
propagationMethod: all
siteSettings:
  950c6040-e386-4f1f-b60a-fec96f0dc055: # democraft
    enabledByDefault: true
    hasUrls: true
    template: services/_entry
    uriFormat: 'services/{slug}'
type: channel
